### ISSUE TITLE
[PipeSystem] Cannot increase tap amount above however much there is on the tap currently

### ISSUE THREAD

**Issue by databobek** [Vanilla-Expanded/VanillaExpandedFramework#97]
Build a chemfuel tap, connect tank to it, fill tank, tap fills with 10 chemfuel, click on tap, try to increase the amount, cannot go greater than 10.

Place more before connecting, say 50, cannot increase above 50 then.

**Comment by BumbleBeetle** [comment]
Hey, to add to this, the bug is independent of any mod, it effects all of the pipe systems. None of the tap buildings can raise their maximum output above the size of the stack already on them and can only do so when they are empty. The exception being the nutrient paste feeder, which can't increase it's max size at all, even if empty or even if it's decreased first.

I did a little testing and the apparent cause of the bug seems to be these sections of code, one for the +1 and +10 buttons:
https://github.com/Vanilla-Expanded/VanillaExpandedFramework/blob/30c157538852479d62f75ddb167a86875013f5dd/Source/PipeSystem/PipeSystem/Comps/CompConvertToThing.cs#L70-L73 and
https://github.com/Vanilla-Expanded/VanillaExpandedFramework/blob/30c157538852479d62f75ddb167a86875013f5dd/Source/PipeSystem/PipeSystem/Comps/CompConvertToThing.cs#L85-L88
Commenting them out fixes the issue, except again for the nutrient paste feeder, which is broken regardless.
My guess is that this code is to meant stop the player from increasing the output past the maximum stack size for the item, but it's actually reading the current stack size.

**Comment by juanosarg** [comment]
Thanks!
